### ISSUE TITLE
manifest.yaml中类名与main函数不一致导致langbot加载插件出错

### ISSUE THREAD

**Issue by sheetung** [HwlloChen/SendLike#1]
```
execution:
  python:
    path: main.py  # 插件主程序路径，必须与上方插件入口代码的文件名相同
    attr: SendLike  # 插件类名，必须与上方代码中声明的类名相同
```
